spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "John-QA lead"
    email: "johndev@gmail.com"
  onCallSupport:
    -(555) 555-1234